#!/bin/bash
# Auto-generated by neurocontainers CI.
export toolName=openreconi2iexample
export version=1.0.19
export baseDockerImage=vnmd/${toolName}_${version}
# this image is build based on 
# https://github.com/neurodesk/neurocontainers/blob/main/recipes/openreconi2iexample/build.yaml
# source .venv/bin/activate
# cd recipes/openreconi2iexample
# /bin/bash ../build.sh --local-cache