#!/bin/bash
# Auto-generated by neurocontainers CI.
export toolName=arfirecon
export version=1.0.12
export baseDockerImage=vnmd/${toolName}_${version}
# this image is build based on 
# https://github.com/neurodesk/neurocontainers/blob/main/recipes/arfirecon/build.yaml
# source .venv/bin/activate
# cd recipes/arfirecon
# /bin/bash ../build.sh --local-cache
