#!/bin/bash
# Auto-generated by neurocontainers CI.
export toolName=epirecon
export version=0.0.4
# Use the mandatory release registry instead of the optional Docker Hub mirror.
export baseDockerImage=ghcr.io/neurodesk/${toolName}:${version}
