#!/bin/bash
# Auto-generated by neurocontainers CI.
export toolName=synthseg
export version=8.2.0
export baseDockerImage=ghcr.io/neurodesk/${toolName}_${version}:20261010
# this image is build based on 
# https://github.com/neurodesk/neurocontainers/blob/main/recipes/synthseg/build.yaml
# source .venv/bin/activate
# cd recipes/synthseg
# /bin/bash ../build.sh --local-cache
