#!/bin/bash
# Auto-generated by neurocontainers CI.
export toolName=blochsiegertb1mapping
export version=1.0.0
export baseDockerImage=vnmd/${toolName}_${version}
# this image is build based on 
# https://github.com/neurodesk/neurocontainers/blob/main/recipes/blochsiegertb1mapping/build.yaml
# source .venv/bin/activate
# cd recipes/blochsiegertb1mapping
# /bin/bash ../build.sh --local-cache