#!/bin/bash
# Auto-generated by neurocontainers CI; dated scanner package rebuild.
export toolName=frisgo
export version=2.10.0-build20261005
export baseDockerImage=ghcr.io/neurodesk/frisgo_2.10.0:20261005
