#!/bin/bash
# Auto-generated by neurocontainers CI; source image pinned to its dated rebuild.
export toolName=frisgo
export version=2.10.0
export baseDockerImage=ghcr.io/neurodesk/frisgo_2.10.0:20261005
