#!/bin/bash
# Auto-generated by neurocontainers CI.
export toolName=qsmxt
export version=9.19.1
export baseDockerImage=ghcr.io/neurodesk/${toolName}_${version}:20260914
# this image is build based on 
# https://github.com/neurodesk/neurocontainers/blob/main/recipes/qsmxt/build.yaml
# source .venv/bin/activate
# cd recipes/qsmxt  
# /bin/bash ../build.sh --local-cache
