#!/bin/bash
# Auto-generated by neurocontainers CI.
export toolName=qsmxt
export version=9.0.7
export baseDockerImage=vnmd/${toolName}_${version}
# this image is build based on 
# https://github.com/neurodesk/neurocontainers/blob/main/recipes/qsmxt/build.yaml
# source .venv/bin/activate
# cd recipes/qsmxt  
# /bin/bash ../build.sh --local-cache
