#!/bin/bash
# Auto-generated by neurocontainers CI.
export toolName=openmsk
export version=0.1.9
export baseDockerImage=vnmd/${toolName}_${version}
# this image is build based on 
# https://github.com/neurodesk/neurocontainers/blob/main/recipes/openmsk/build.yaml
# source .venv/bin/activate
# cd recipes/openmsk
# /bin/bash ../build.sh --local-cache
